### ISSUE TITLE
Pointcloud overlay on images

### ISSUE THREAD

**Issue by gilduz** [foxglove/studio#2655] opened 2022-01-12 14:21 UTC
Would it be possible to overlay pointcloud data on 2D images on image panel?
I think this would be a great feature for reproducing a similar behaviour of rviz camera.

**Comment by jtbandes** [comment] 2022-01-12 18:08
Thanks for the request! We are already tracking this feature at https://github.com/foxglove/studio/issues/2181 and you can follow that issue for updates. In the meantime, you can use Image Markers to add markers on your 2D images, but you'll need to transform them into image coordinates yourself. Some examples to get you started with image markers are here: https://foxglove.dev/blog/annotate-your-robots-camera-images-with-image-markers

Duplicate of #2181

**Closed by jtbandes** 2022-01-12 18:08 UTC
Labels: feature
