### ISSUE TITLE
RGB Point cloud color is wrong

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#4680] opened 2022-10-20 13:03 UTC
**Description**

- Open [this bag file][1] in Studio (web or desktop).
- Open the 3d panel and enable the only point cloud topic
- Notice the point cloud is red (sometimes).
- If the cloud is not red, change the color to flag then back to RGB.

Here is a screenshot showing the same point cloud in Studio and RViz.

<img width="1438" alt="Screen Shot 2022-10-20 at 9 42 53 PM" src="https://user-images.githubusercontent.com/84792/196956072-6722523e-9320-4046-9f6d-9797ba63e7f6.png">

---
- Version: 1.29.0
- OS: Mac / Web / Chrome
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): bag
- ROS distro (if applicable): Noetic

[1]: https://drive.google.com/file/d/1RAxFlp4IEncfvcA1wdyNTOQYgUE7XJYH/view?usp=sharing

**Comment by amacneil** [comment] 2022-10-20 21:40
Shouldn't we use the same color byte order as rviz by default, when rendering `PointCloud2`?

**Comment by defunctzombie** [comment] 2022-10-21 22:16
Re-opened this bug since this did work in legacy 3d. Tho it might be considered a duplicate of https://github.com/foxglove/studio/issues/4483?

**Comment by jtbandes** [comment] 2022-10-21 22:16
Duplicate of #4483

**Closed by jtbandes** 2022-10-21 22:16 UTC
Labels: bug
