### ISSUE TITLE
Ros2 MarkerArray with not timestamp does not show

### ISSUE THREAD

**Issue by tonynajjar** [foxglove/studio#6991] opened 2023-10-13 15:42 UTC
**Description**

- Version:1.72.0
- Platform: desktop
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): foxglove bridge ROS2

**Steps To Reproduce**

I am publishing a MarkerArray which I can visualize in Rviz but not in Foxglove:

```
markers:
- header:
    stamp:
      sec: 0
      nanosec: 0
    frame_id: base_link
  ns: collision_points
  id: 0
  type: 8
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.1
    y: 0.1
    z: 0.0
  color:
    r: 1.0
    g: 0.0
    b: 0.0
    a: 1.0
  lifetime:
    sec: 2
    nanosec: 0
  frame_locked: false
  points:
  - x: -2.999214073461749
    y: 0.5856084967843912
    z: 0.0
  - x: -2.999214073461749
    y: 0.5856084967843912
    z: 0.0
  - x: -2.999214073461749
    y: 0.5856084967843912
    z: 0.0
  - x: -2.999214073461749
    y: 0.5856084967843912
    z: 0.0
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
```

I noticed that when the message is given a recent timestamp, it does appear in foxglove however it breaks in rviz for reasons I don't know. I would expect foxglove to behave like Rviz when not given a timestamp as described [here](http://wiki.ros.org/rviz/DisplayTypes/Marker#:~:text=Note%20that%20the,the%20current%20time.)

**Comment by jtbandes** [comment] 2023-10-13 16:06
Could you share a bag file or script to reproduce the issue?

**Comment by tonynajjar** [comment] 2023-10-13 16:29
I was trying to record a bag but the issue doesn't reproduce in the bag. It only happens in a live foxglove bridge connection. I don't have time today to write a full script anymore but basically this is the message to publish:


```
    visualization_msgs::msg::MarkerArray marker_array;
    visualization_msgs::msg::Marker marker;
    marker.header.frame_id = "base_link";
    marker.header.stamp = rclcpp::Time(0, 0);
    marker.ns = "collision_points";
    marker.id = 0;
    marker.type = visualization_msgs::msg::Marker::POINTS;
    marker.action = visualization_msgs::msg::Marker::ADD;
    marker.scale.x = 0.1;
    marker.scale.y = 0.1;
    marker.color.r = 1.0;
    marker.color.a = 1.0;
    marker.lifetime = rclcpp::Duration(2, 0);
    geometry_msgs::msg::Point p;
    p.x = 1.0;
    p.y = 1.0;
    p.z = 0.0;
    marker.points.push_back(p);
```

I should also note that it's a simulation so using sim time

**Comment by achim-k** [comment] 2023-10-18 15:13
> I would expect foxglove to behave like Rviz when not given a timestamp as described [here](http://wiki.ros.org/rviz/DisplayTypes/Marker#:~:text=Note%20that%20the,the%20current%20time.)

This remind me of https://github.com/foxglove/studio/issues/6893 in which I first heard of publishing with a zero timestamp. I don't know yet if we want to mirror Rviz behavior in Studio. In your case, since you publish `visualization_msgs/Marker`, you could achieve the desired effect by setting `marker.frame_locked` to `true`.

**Comment by achim-k** [comment] 2023-10-23 22:45
@tonynajjar is the above mentioned workaround working for you?

**Comment by tonynajjar** [comment] 2023-10-27 14:42
hey, sorry for the delay, indeed this workaround does work. I think it would be useful to document this somewhere or fix it such that it works without this workaround. Thanks for the tip

**Comment by achim-k** [comment] 2023-10-30 16:00
Great to hear, will close this issue then.

**Closed by achim-k** 2023-10-30 16:00 UTC
Labels: bug
