### ISSUE TITLE
Layout change detection should only show changes when the layout state is different from saved state

### ISSUE THREAD

**Issue by bclinkinbeard** [foxglove/studio#2068] opened 2021-11-02 17:19 UTC
Given a saved layout that includes a Plot panel with the legend open, close the legend and then reopen it. The layouts panel reports a change to the layout, even though the state matches the initial value.

This is reproducible on https://studio.foxglove.dev/

**Steps To Reproduce**
See above.

**Expected Behavior**
Layout state is matched to the initial state, and there are no pending changes.

**Actual Behavior**
Layout panel still reports pending changes, even though the state is the same.

**Comment by asyncanup** [comment] 2021-11-12 23:44
@defunctzombie
1. Could you clarify why this is a feature, not a bug?
2. Do you have an ETA for implementing this change?

**Comment by defunctzombie** [comment] 2021-11-13 00:21
@asyncanup Every panel has a configuration (or state) object that it saves as part of the layout. The Plot panel considers the legend toggle state as part of this persisted configuration so when a user toggles the legend the plot panel saves the new state. Studio considers every state save as an indicator the layout is "changed".

I marked this as a feature since the behavior currently works as designed (panel says save this new state for me so the layout is considered "changed") and the feature is to enhance that change detection logic to either doing more detection around whether the state is different from the saved state or possibly having some features like the state of the legend not be relevant or part of the saved layout state.

Whether it's a bug vs feature is semantics. Certainly it's undesirable? annoying? behavior from your standpoint since visually the layout is unchanged but I'd also argue nothing is broken or preventing use of the app.

There is no ETA for implementing this change.

**Comment by defunctzombie** [comment] 2022-03-10 00:40
@jtbandes See: https://github.com/foxglove/nvidia-issue-tracker/issues/42#issuecomment-1063525384

**Closed** 2022-03-10 23:52 UTC
Labels: feature, ux
