### ISSUE TITLE
Extend ImageMarker to support text display

### ISSUE THREAD

**Issue by windzu** [foxglove/studio#4413] opened 2022-09-13 07:16 UTC
In the image panel, the ImageMarkers supported by foxglove are inherited from ros, but ros did not seem to consider the task of 2d detection at the beginning of its design, so it does not support the display of text.

For 2d detection tasks, category display is also an important requirement. So I hope you can add an extension to the text display on the basis of ImageMarkers

**Comment by defunctzombie** [comment] 2022-09-13 14:09
@jtbandes Do you think this is a good candidate for the BYOD epic via a foxglove.TextAnnotation message next to our existing ImageAnnotation messages?

**Comment by jtbandes** [comment] 2022-09-13 15:06
Could be a good idea, time permitting.

**Comment by jtbandes** [comment] 2022-09-13 15:06
Duplicate of https://github.com/foxglove/schemas/issues/24

**Closed by jtbandes** 2022-09-13 15:06 UTC
Labels: feature
