### ISSUE TITLE
MarkerArray display error in Vmware Ubuntu20.04

### ISSUE THREAD

**Issue by darduck18** [foxglove/studio#3208] opened 2022-04-19 09:32 UTC
**Description**

I have encountered the same problem as #2727, windows is ok but Ubuntu failed.
And I tried other computers with the same problem.
Can i fix it in virtual machine?

- Version:V1.7.0
- OS:Vmware Ubuntu20.04

**Steps To Reproduce**

open example datasource /semantic_map

**Expected Behavior**

**Actual Behavior**
![20220419172503](https://user-images.githubusercontent.com/23479151/163973546-3d04efa3-306e-479b-9b3e-5a5a25264065.jpg)
![20220419172522](https://user-images.githubusercontent.com/23479151/163973571-7cf056df-9f4d-4a50-b842-c2e64aa44204.jpg)
![20220419172533](https://user-images.githubusercontent.com/23479151/163973581-e116cf6d-7fec-4b15-b94f-afb849c59c60.jpg)

**Comment by jtbandes** [comment] 2022-04-19 19:45
Hi, thanks for the report. Based on the error message, which comes from [here](https://github.com/foxglove/regl-worldview/blob/92df7aad8d28d15a811d5daaed672261c507e27a/src/commands/Lines.js#L533), this error doesn't seem like it should be platform-specific and looks like more of a logic error. Could you share a video of steps to reproduce the error? I have tried enabling the /semantic_map topic and playing through the whole sample dataset on ubuntu, and I can't reproduce the issue. Does it happen 100% of the time for you?

**Comment by darduck18** [comment] 2022-04-20 00:03
> Hi, thanks for the report. Based on the error message, which comes from [here](https://github.com/foxglove/regl-worldview/blob/92df7aad8d28d15a811d5daaed672261c507e27a/src/commands/Lines.js#L533), this error doesn't seem like it should be platform-specific and looks like more of a logic error. Could you share a video of steps to reproduce the error? I have tried enabling the /semantic_map topic and playing through the whole sample dataset on ubuntu, and I can't reproduce the issue. Does it happen 100% of the time for you?

thanks for your reply.
it happen 100% for my vmware workstation,I just enable /semantic_map topic
Others computer's issue as below.

![20220420075146](https://user-images.githubusercontent.com/23479151/164119572-2372556f-443b-49cf-a5fb-3d8c2150ac68.jpg)

 as #2727, i think it happen only in virtual machine ubtuntu.

**Comment by jtbandes** [comment] 2022-04-20 14:17
What operating system & architecture is your host machine?

**Comment by jtbandes** [comment] 2022-04-20 17:27
Since we can't reproduce this issue, it would help if you can set a breakpoint where the error occurs using the Chrome debugger, and share a screenshot of the variable values, like this:

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/14237/164288341-da9e2411-9f77-4a30-84de-acbccd798830.png">


Notice in my screenshot, `numInputPoints` is 2820 while `instances` and `poses` are 2819 (that's expected because 2820 points turn into 2819 line segments).

It would also be helpful to see the state after the call to `groupLinesIntoInstancedLineLists()` inside WorldMarkers:

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/14237/164288222-f7c09f7e-1aea-4fa4-a5e6-addb0069a634.png">

This is where the original 102 `lineStrip` markers are grouped into one line with 2820 points. NaN points are used to separate multiple segments:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/14237/164288362-7b43d899-b4d3-4d96-920a-de4d166e2334.png">

**Comment by jtbandes** [comment] 2022-04-21 20:06
If you could get the debug screenshots from https://studio.foxglove.dev instead of the desktop app, it should have better variable names (fixed in https://github.com/foxglove/studio/pull/1880)

**Comment by darduck18** [comment] 2022-04-22 12:51
> If you could get the debug screenshots from https://studio.foxglove.dev instead of the desktop app, it should have better variable names (fixed in #1880)

ok,i got it.
![20220422204704](https://user-images.githubusercontent.com/23479151/164717336-795d5131-7998-4023-9a45-1d730e4620da.jpg)
![20220422204714](https://user-images.githubusercontent.com/23479151/164717340-ddebcef0-0a0e-40e4-98d6-567322f04717.jpg)
![20220422204723](https://user-images.githubusercontent.com/23479151/164717346-ab337567-2ee6-4cf5-b84d-8be4a3e5a4dc.jpg)

By the way, i check this issue in vm ubuntu16.04,it works fine.

**Comment by jtbandes** [comment] 2022-04-22 20:17
>  ![](https://user-images.githubusercontent.com/23479151/164717336-795d5131-7998-4023-9a45-1d730e4620da.jpg)

In this screenshot, `instances` is 2819, and `poses.length` is also 2819, so there should be no error. Is there sometimes an error and sometimes no error?

**Comment by darduck18** [comment] 2022-04-26 13:01
> > ![](https://user-images.githubusercontent.com/23479151/164717336-795d5131-7998-4023-9a45-1d730e4620da.jpg)
> 
> In this screenshot, `instances` is 2819, and `poses.length` is also 2819, so there should be no error. Is there sometimes an error and sometimes no error? Can you move the breakpoint to `console.error` so it only stops when there is an error?

I check many times,there is no error,but it also display green background.I think the issue is no case by this error.

**Comment by defunctzombie** [comment] 2022-05-02 23:37
From my reading of the issue it sounds like the problem originally shown in the console (expected poses count was wrong) is no longer happening so I don't understand why it appeared in the original console logs.

We've not been able to reproduce this issue so our latest thinking is that its specific to your VM or graphics driver. Given the disconnect in our ability to reproduce this I am not sure we're gonna be able to provide a fix. If you are able to grab the source code for Studio and run a development build you might be able to poke around and figure something out. We are actively moving to a different rendering engine for the 3d panel. That work is still a month or more away but it might help in cases like this one.

I'm going to close this issue out since I don't see what else we can troubleshoot here. If you do learn more please comment with a way we can attempt to reproduce.

**Closed by defunctzombie** 2022-05-02 23:37 UTC
Labels: bug
