### ISSUE TITLE
Load multiple rosbag files of the same time range in Foxglove studio

### ISSUE THREAD

**Issue by konsgken** [foxglove/studio#4870] opened 2022-11-22 07:56 UTC
I would like to import  and visualize  two rosbag files of the same time range simultaneously (e.g. one rosbag file that will include only time series data, and another one that will include images and annotations). Is it possible to do that in foxglove?

**Comment by jtbandes** [comment] 2022-11-22 18:04
It is not currently possible, you would need to merge the bag files first.

Duplicate of https://github.com/foxglove/studio/issues/2120, related to #3174

**Closed by jtbandes** 2022-11-22 18:04 UTC
Labels: feature
