### ISSUE TITLE
TypeError: Failed to fetch layouts popup

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1973] opened 2021-10-13 00:22 UTC
**Description**
Sometimes I leave FGS open, and when I come back to it I see this error:

![image (1)](https://user-images.githubusercontent.com/637671/137046071-fc068722-0903-42bc-9605-159870385639.png)

I'm not sure if this is related to my computer suspending, or maybe internet dropping out when I unplug docking station.

- Version: v0.19.0
- OS: Linux

**Steps To Reproduce**
It's hard to say exactly when this happens, but I just leave Studio open for a while.

**Desired Experience**
I think we could make this way less intrusive.
- We could make a few retry attempts before showing notification to the error
- When there is an error, we could make it much more subtle
- When I'm reconnected the error should go away
- Even better: server connection status (online/offline) could show up in a status bar at the bottom of app (we've talked about introducing something like that for a while)

cc @jtbandes @2metres for thoughts

**Comment by defunctzombie** [comment] 2022-04-14 15:52
I don't think we should show the user notifications like this for a failure to sync a layout and instead should track the error in the layout browser and show users a simpler error (or no notification at all).

**Comment by jtbandes** [comment] 2022-04-15 20:14
I personally haven’t seen this error for a long time. Is anyone still seeing it or do we have some idea of how to reproduce? We could do some work to improve the error but it would be hard to test in a realistic scenario if we don’t have steps to reproduce.

**Comment by defunctzombie** [comment] 2022-04-16 01:49
I am going to close this. After thinking about this some more, I think we _have_ done some work since this was filed to reduce notifications on layout sync failures. If we encounter something specific we should re-visit. I want to emphasize yet again that these notifications should be meaningful language for the user with the ability to surface more details for support/debugging via click-through. So when we do encounter notifications like this we should file them and resolve them.

**Closed by defunctzombie** 2022-04-16 01:49 UTC
Labels: ux
