### ISSUE TITLE
Timestamp is not correct when playing .mcap file

### ISSUE THREAD

**Issue by felixf4xu** [foxglove/studio#4059] opened 2022-08-05 08:23 UTC
**Description**

Hi,

I have created a .mcap file and I can play it in Foxglove Studio, now I'm trying to use the next/previous button to play the data frame by frame.

There seems to be a timestamp indicating current frame's time, but if I click the previous/next button back and forth, the timestamp is changing every time, it's not reading from my original frame data's timestamp.

- Version: 1.20
- OS: Windows
- Data source ( self-created mcap file )

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/84662027/183030636-6452b02f-5d64-4278-8dca-1fcef135a3ad.png)

1. remember current timestamp,
2. click the previous button once, then the next button once, 
3. check the timestamp if equal to the timestamp in step 1.

**Expected Behavior**

the timestamps are same, and it's from the timestamp within the .mcap file.

**Actual Behavior**

the timestamps are not same, and it seems to be random.

**Comment by defunctzombie** [comment] 2022-08-05 15:18
Duplicate of: https://github.com/foxglove/studio/issues/3872

I am working on a fix here: https://github.com/foxglove/studio/pull/4045

**Comment by jtbandes** [comment] 2022-08-05 22:02
Duplicate of https://github.com/foxglove/studio/issues/3872

**Closed by jtbandes** 2022-08-05 22:02 UTC
Labels: bug
