### ISSUE TITLE
Add renamable title for every panel type

### ISSUE THREAD

**Issue by jk-ethz** [foxglove/studio#4853] opened 2022-11-18 10:16 UTC
Currently, some panel types such as plots have configurable titles.
Wouldn't it make sense to have this feature implemented in the base class of every panel and let all panels have that "title" property?
Currently, for panels, such as "Gauge" I would love to have some indication to the user to what the gauge is actually displaying. To that end, a freely configurable title would enable making layouts much more self-explanatory.
Also, just having the panel type as a fixed title is redundant, since the user typically sees that this panel is a "Gauge".

**Comment by jtbandes** [comment] 2022-11-18 17:37
Duplicate of https://github.com/foxglove/studio/issues/4174

**Closed by jtbandes** 2022-11-18 17:37 UTC
Labels: feature
