### ISSUE TITLE
3D scene Markers disappear randomly

### ISSUE THREAD

**Issue by sionyx** [foxglove/studio#2718] opened 2022-01-24 09:20 UTC
**Description**

- Version: 0.27.0
- OS: MacOS Desktop or Web

**Steps To Reproduce**
- Foxglove ws protocol
- Send messages with MarkerArray containing 2 markers (mesh and text)
- send rate: 1 message per 0.1 second 
- video play rate is 0.01x, but is behaves the same on play rate 1.0x 

https://user-images.githubusercontent.com/1351998/150753513-9e281566-eb5c-4733-af38-7afe31d2486b.mov

Timestamp of markers same with timestamp of message

![image](https://user-images.githubusercontent.com/1351998/150753958-f782f8a4-4773-460f-8222-1e4cae2cec12.png)

Timestamp of message is set in message frame header:

![image](https://user-images.githubusercontent.com/1351998/150754075-eec6ced5-0f23-413f-88a5-98dbc8fa41ba.png)

**Expected Behavior**
- Markers are always visible on scene

**Actual Behavior**
- Markers are disappear and appear again in random moments.

**Comments**
- it is not related to loading mesh model - it loads successfully ones (checked in Chrome Developer Console) and text marker disappears at the same time.
- it is not related to tf - as Roman said: I also see you are rendering in the Innopolis frame which matches your marker frame_id so I would agree tf is not related to the issue here.
- it is not related to play rate - same behaviour on different rates

Discusion archive: https://foxglove.slack.com/archives/C028UEY858S/p1642942399069300

**Comment by defunctzombie** [comment] 2022-01-24 16:44
@sionyx In your video above there is a problem indicator for the data source:

![image](https://user-images.githubusercontent.com/84792/150826214-6a7b7429-caae-4615-b0cd-ee3bfc873a10.png)

What are the problems the data source is reporting?

**Comment by sionyx** [comment] 2022-01-24 16:48
> What are the problems the data source is reporting?

@defunctzombie sometimes my backend advertise tf and tf_static channels twice with the same channel_id. Seems that it should not lead to discussed problem.

**Comment by defunctzombie** [comment] 2022-01-24 16:58
> @defunctzombie sometimes my backend advertise tf and tf_static channels twice with the same channel_id. Seems that it should not lead to discussed problem.

Can you fix that up and see if the problem still happens? Changing _tf_ is something that will impact the overall rendering of the 3d panel.

I've also made an example websocket server: https://gist.github.com/defunctzombie/83110a6314e4ccb8d278a5acc77effe1 where I've attempted to reproduce the publish pattern I am seeing in your video. This server publishes a marker message every second with a stamp incrementing by 0.01 seconds. Using this server I've not been able to reproduce your issue. This makes me think its not just how the markers are published but how other messages are impacting the 3d panel.

**Comment by defunctzombie** [comment] 2022-01-24 17:07
For additional reference here is the layout I am using:

![image](https://user-images.githubusercontent.com/84792/150830272-62c9a7d0-10d5-4b7d-a7a8-1d32428edb7f.png)

**Comment by sionyx** [comment] 2022-01-24 17:19
Let me some time to play with your test server. I'll respond as soon as posible

**Comment by sionyx** [comment] 2022-01-25 13:43
@defunctzombie Roman, I finally modified your server to let it play my messages. Actually just 2 messages is enough to reproduce flashing. You can find them in file [ws-dump-datalines-hex](https://gist.github.com/sionyx/1d2476ca2cd88a16a119e6dd17a5c89e#file-ws-dump-datalines-hex). First line leads to hide marker, second one leads to show it again.

Here is gist with updated server and dump-file https://gist.github.com/sionyx/1d2476ca2cd88a16a119e6dd17a5c89e

I compare two messages and the only difference are positions and orientations. Positions are pretty same and look reasonable. May be something wrong with orientations?

**Comment by defunctzombie** [comment] 2022-01-25 16:26
Thanks for providing that additional info and example.

As we discussed in Slack, the marker disappears because its `header.stamp` time is _after_ the `end time` on your data source. The 3d panel considers this marker outside the time bounds and removes it.

Closing this since we've found the root cause. Feel free to re-open if you find that markers disappear even when their `header.stamp` time occurs within the dataset time bounds.

**Closed by defunctzombie** 2022-01-25 16:26 UTC
Labels: bug

**Comment by jtbandes** [comment] 2022-01-25 18:49
> BTW there is some error in console:
> ![image](https://user-images.githubusercontent.com/1351998/150987501-29a18b81-a7bc-4fd1-bf8b-d4f753928d49.png)
> It would be nice to show WebGL error somewhere.

If this error is reproducible could you please file a new issue with steps to reproduce?

**Comment by sionyx** [comment] 2022-01-25 19:05
@jtbandes I've seen this message couple of times in console by chance. If I will found way to reproduce I file issue. And actually I haven't seen errors itself, just this message about too many errors.
