### ISSUE TITLE
3D (Beta) Does Not Respect Collada up_axis

### ISSUE THREAD

**Issue by cody-sheff** [foxglove/studio#4416] opened 2022-09-13 17:49 UTC
Currently, there's no option to have the 3D (Beta) tab respect the Collada up_axis argument like the 3D tab does, which can lead to issues when importing those meshes.

**Comment by jtbandes** [comment] 2022-09-13 18:01
Prior work on this issue:

- https://github.com/foxglove/studio/issues/2706
- https://github.com/foxglove/studio/pull/2749

**Comment by defunctzombie** [comment] 2022-09-14 03:55
Added the bug label because this is a regression in explicitly added and supported functionality in the 3d panel.

**Comment by jtbandes** [comment] 2022-09-16 21:56
Fixed in https://github.com/foxglove/studio/pull/4442

**Closed by jtbandes** 2022-09-16 21:56 UTC
Labels: bug, new3d
