### ISSUE TITLE
3D Camera FOV distorted

### ISSUE THREAD

**Issue by Senaxius** [foxglove/studio#5151] opened 2023-01-14 19:35 UTC
**Description**
When displaying a camera FOV in the 3d panel, I noticed that the image (ros2 image_raw message) was weirdly stretched in the 3D panel compared to the image panel:

![Screenshot_20230114_200345](https://user-images.githubusercontent.com/64868177/212491767-8f688a9b-6522-4575-8158-5fca12c4f96a.png)

I thought this was due to wrong calibration send by the camera_info msg, so I tested how the values send by the camera_info changed the 3D Fov.
I striped everything besides resolution and the camera matrix, which only contains focal length and the center of the picture. 
When I send a completely square picture, with a 1000x1000 resolution and identical x and y focal length (800 in this case), the Fov has a 1:1 ratio, as it should have:
```
self.msg = CameraInfo()
self.msg.width = 1000
self.msg.height = 1000
self.msg.p = [ 800.0, 0.0, 500.0, 0.0, 0.0, 800.0, 500.0, 0.0,  0.0, 0.0, 1.0, 0.0]
```
![Screenshot_20230114_202310](https://user-images.githubusercontent.com/64868177/212492554-bb42d319-8403-4339-b2cd-b0187d17b2f3.png)

But when I send a camera info with a 2:1 ration, this happens:
```
self.msg = CameraInfo()
self.msg.width = 2000
self.msg.height = 1000
self.msg.p = [ 800.0, 0.0, 1000.0, 0.0, 0.0, 800.0, 500.0, 0.0,  0.0, 0.0, 1.0, 0.0]
```
![Screenshot_20230114_202505](https://user-images.githubusercontent.com/64868177/212492615-27f10d79-cafc-44bb-84c2-48a13cdbeb93.png)

This is definitely not 2:1, and explains the weird stretch of the picture.

I'm quite a beginner in the robotic world, so it's quite possible that I messed something up, but after multiple hours of troubleshooting I really don't know what to try anymore.

- Version:
ros humble
Foxglove Studio version 1.29.0

- Platform:
Arch Linux
ros2 running in a docker container

**Steps To Reproduce**
Just run this python publisher:
```
import rclpy
from rclpy.node import Node
import yaml

from sensor_msgs.msg import CameraInfo

class camera_info_publisher(Node):
    def __init__(self):
        super().__init__("camera_info_publisher") 

        self.publisher_ = self.create_publisher(
            msg_type=CameraInfo, topic="camera_info", qos_profile=10)
  
        self.msg = CameraInfo()
        self.msg.width = 2000
        self.msg.height = 1000
        self.msg.p = [   800.0,    0.0,     1000.0,     0.,
                            0.0, 800.0,     500.0,     0., 
                            0.0,    0.0,       1.0,     0.]
        self.publisher_.publish(self.msg)



def main(args=None):
    rclpy.init(args=args)
    node = camera_info_publisher()  
    rclpy.spin(node)
    rclpy.shutdown()


if __name__ == "__main__":
    main()

```

**Comment by jtbandes** [comment] 2023-01-14 19:39
Duplicate of https://github.com/foxglove/studio/issues/4852, fixed in v1.35

**Closed by jtbandes** 2023-01-14 19:39 UTC
Labels: bug
