### ISSUE TITLE
cant connect to ROS stream via docker

### ISSUE THREAD

**Issue by an99990** [foxglove/studio#3412] opened 2022-05-19 19:52 UTC
**Description**
I am running a docker container in which theres is a ros2 node running. I would like to visualize the images in foxgloves.
I expose the IP adress when running the docker.
`
docker run --expose 8080 -it -p 8080:8080 --runtime nvidia --privileged -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix buffer`

Open connection steps

Foxglove does not seem to be able to connect to the server

![image](https://user-images.githubusercontent.com/87030365/169391865-1c647025-b5ea-49b8-944f-eaee3384257d.png)

error: 

![image](https://user-images.githubusercontent.com/87030365/169392531-86780424-41a2-4622-8855-11fa8f7c4aec.png)

**Comment by rgov** [comment] 2022-05-19 20:00
I think you have two problems:

1. You should be connecting to the Websocket of the Rosbridge server. Port 8080 is set up to be Foxglove's web server port, so Rosbridge must be running on another port. It is usually on port 9090.

2. When you're running in a container, the hostname `localhost` refers to *the container itself* and not to the host operating system. So if you connect to `localhost` it would try to connect to some other service running inside the same container.

    On the host, you can use `ip addr` to find the address of the Docker interface (called something like `docker0`). It is often `172.17.0.1`. Then you could connect Foxglove Studio to `ws://172.17.0.1:8080`.

If you don't need to be using Docker I would suggest using the standalone app.

**Comment by an99990** [comment] 2022-05-19 20:04
hi @rgov thank you for answering so quickly. I have unfortunalty no choice but to run the docker to access my ros node. What do you suggest me to change.
`docker run --expose 9090 -it -p 9090:9090 --runtime nvidia --privileged -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix buffer`

?

**Comment by an99990** [comment] 2022-05-19 20:07
should i run the docker differently ? 

![image](https://user-images.githubusercontent.com/87030365/169395633-e7455e62-0ee0-45f1-b656-b381abf1a94f.png)

![image](https://user-images.githubusercontent.com/87030365/169395659-9f44e016-778d-4184-ad0f-dd0a67c21576.png)

**Comment by rgov** [comment] 2022-05-19 20:19
Sorry I misunderstood, I thought you were running Foxglove Studio itself in a container.

So your ROS nodes are running inside the container, and this includes a [rosbridge_suite](https://github.com/RobotWebTools/rosbridge_suite) Rosbridge server. Then yes, use `-p 9090:9090`, I don't think you also need `--expose`. 

The port number 9090 is defined here:

https://github.com/RobotWebTools/rosbridge_suite/blob/d9c4f3973da27920fb9963f1717a362b2ba6e7e1/rosbridge_server/scripts/rosbridge_websocket.py#L110

Then `ws://localhost:9090` should work from Foxglove Studio.

**Comment by an99990** [comment] 2022-05-20 12:16
HI thank you @rgov for your answer
I did as you told and it does not seem to be working .

just so were on the same page, the docker that i run has the ros2 node running

how i run it
`docker run -it -p 9090:9090 --runtime nvidia --privileged --gpus all -it --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 zed_torch`

It keeps waiting for connection 

![image](https://user-images.githubusercontent.com/87030365/169526242-e58fda3b-bf99-44fa-9332-f20bbae27695.png)

**Comment by rgov** [comment] 2022-05-20 14:50
And the container and Foxglove Studio are running on the same host system? Can you provide proof that the Rosbridge server is actually running inside the container (e.g., `docker exec <your running container id> ps -awx`, `docker exec <your running container id> netstat -plnt`)

Are you using the Foxglove Studio app or using it from the web browser? Open the Developer Tools (in app, View -> Advanced -> Toggle Developer Tools) and look at the Console. Does it give any more information about not being able to connect?

**Comment by rgov** [comment] 2022-05-24 15:17
There are no ROS nodes running inside your `zed_torch` container.

**Comment by an99990** [comment] 2022-05-24 16:15
![image](https://user-images.githubusercontent.com/87030365/170083613-863ffbca-9b50-4d4e-a168-1c5c3f23076e.png)

**Comment by rgov** [comment] 2022-05-24 19:28
That looks slightly better, but as mentioned you need to also run a rosbridge_server node from the [rosbridge_suite](https://github.com/RobotWebTools/rosbridge_suite) package inside the container.

**Comment by an99990** [comment] 2022-05-24 19:44
![image](https://user-images.githubusercontent.com/87030365/170119255-a6f892ea-a512-479b-a19b-990349c55a70.png)

**Comment by rgov** [comment] 2022-05-24 19:55
You didn't pass `-p 9090:9090` to the container that is running your rosbridge server. Also it is recommended that you run your nodes and the rosbridge server in the same container.

If you need further support, I suggest closing this issue and asking on https://answers.ros.org/. The issue is not with Foxglove Studio, but seem to be misconceptions about how Docker and/or ROS work.

**Closed** 2022-05-24 19:57 UTC
Labels: bug
