### ISSUE TITLE
3D pannel shows above full screen panel

### ISSUE THREAD

**Issue by clementchef** [foxglove/studio#2808] opened 2022-02-09 00:00 UTC
3D panel sometimes pop on top of the full screen panel.
![image](https://user-images.githubusercontent.com/66749666/153096010-0b370f7c-3b37-4f97-b6f5-60b344c65dda.png)

- Version: 0.25.1
- OS: ubuntu 18

**Steps To Reproduce**
Not completly sure. Seems pretty random. This was in live mode (not bag mode).

**Expected Behavior**

**Actual Behavior**

**Comment by defunctzombie** [comment] 2022-02-10 06:37
I've tried to reproduce this on my Mac in chrome but haven't been able to so far. I also tried with the desktop app on my Mac and could not reproduce (trying a few things like changing window size).

Any steps you can come up with to reproduce would be helpful. It's also possible its specific to running on ubuntu linux and has something to do with your video graphics.

Another thing I'd recommend is updating to a newer version of studio. We're on 0.29.0 now. I am not recalling anything specific we fixed with full screen panels but its possible there were some changes that have impacted this layering.

**Comment by amacneil** [comment] 2022-02-28 23:27
@clementchef closing per your Slack message - please reopen if this starts happening again.

**Closed by amacneil** 2022-02-28 23:27 UTC
Labels: bug, customer request
