### ISSUE TITLE
3D beta panel starting with all subscribed

### ISSUE THREAD

**Issue by bertaveira** [foxglove/studio#3811] opened 2022-07-11 07:12 UTC
**Description**
Currently the new 3D beat panel starts by subscribing to all topics. In our case we have very dense lidars that would require incredibly fast connection so when connecting to the robot wirelessly the fact that it subscribes to everything make both foxglove and rosbridge crash since it is trying to send at a data rate over 100x times the one available.

Would be nice to be able to use this panel but it would require it to start as not subscribing to anything because in live connection there is not way to even add it and unsubscribe from topics before it crashes

**Comment by defunctzombie** [comment] 2022-07-11 14:11
Related: https://github.com/foxglove/studio/issues/3692

**Comment by jtbandes** [comment] 2022-09-08 17:21
Duplicate of #3692, fixed in #3839

**Closed by jtbandes** 2022-09-08 17:21 UTC
Labels: ux
