### ISSUE TITLE
Support Livox Lidars

### ISSUE THREAD

**Issue by arjunskumar** [foxglove/studio#1946] opened 2021-10-07 04:31 UTC
How can I visualize point cloud data from livox horizon lidar?

**Comment by arjunskumar** [comment] 2021-10-07 04:47
Yes, I'm using ROS. Actually, the SLAM algorithms output a point cloud map of type sensor_msgs/PointCloud2.

**Comment by amacneil** [comment] 2021-10-07 05:50
Alright, it should work out of the box then! Just select the topic in the 3d panel. Let us know if you run into any issues.

https://foxglove.dev/docs/panels/3d

**Comment by defunctzombie** [comment] 2021-10-07 13:43
@arjunskumar Can you share a bag file so we can play it and see if we experience the same issues?

**Comment by amacneil** [comment] 2021-11-19 04:39
Closing this issue since the original request is supported.

@arjunskumar if you are still having performance issues, please open a new ticket with an example bag to reproduce the issue. Thanks!

**Closed by amacneil** 2021-11-19 04:39 UTC
Labels: feature
