### ISSUE TITLE
Can't receive tf_static when connected to live ROS2 using websocket

### ISSUE THREAD

**Issue by chenjunnn** [foxglove/studio#1987] opened 2021-10-18 12:26 UTC
**Description**
In 3D panel, the tf_static and marker cannot be correctly displayed.

- Version: 0.19
- OS: Windows 11

**Expected Behavior**
![image](https://user-images.githubusercontent.com/57067221/137729777-63cd0108-22bc-42cb-a8bb-41abf15e24f2.png)

**Actual Behavior**
![image](https://user-images.githubusercontent.com/57067221/137729873-40824edd-7b4e-47ba-8a5b-75f5dfd30c76.png)

**Comment by defunctzombie** [comment] 2021-11-03 23:33
@sink0918 Which ros version are you using? And are you running ros on the same computer as studio or a different computer?

**Comment by sink0918** [comment] 2021-11-06 05:36
> @sink0918 Which ros version are you using? And are you running ros on the same computer as studio or a different computer?

I am using Galactic, and I'm running ROS on a remote Ubuntu 20.04 and Studio on local Windows 11.

**Comment by defunctzombie** [comment] 2021-11-08 22:03
@sink0918 Thanks. Another question to help us reproduce the same environment you have. What is publishing the `/tf_static` topic?

**Comment by sink0918** [comment] 2021-11-16 01:15
@defunctzombie I'm using realsense ROS2 wrapper, and `/tf_static` is published from [here](https://github.com/IntelRealSense/realsense-ros/blob/b30a25b400bddf28292058968fb69d96f9e1af9b/realsense2_camera/src/base_realsense_node.cpp#L2329). 

And the `_static_tf_broadcaster` is constructed [here](https://github.com/IntelRealSense/realsense-ros/blob/b30a25b400bddf28292058968fb69d96f9e1af9b/realsense2_camera/src/base_realsense_node.cpp#L214)

**Comment by sink0918** [comment] 2021-11-24 15:44
I have tested with `static_transform_publisher` in package `tf2_ros`, and Studio still receives nothting from `tf_static`.

Here is the code in my launch file:
```python
gimbal_camera_translation = ['0.5', '0', '0.2']

Node(
    package='tf2_ros',
    executable='static_transform_publisher',
    arguments=gimbal_camera_translation + \
    ['0', '0', '0', 'gimbal_link', 'camera_link']
)
```

**Comment by defunctzombie** [comment] 2021-12-03 16:41
@chenjun00 Does `ros2 topic echo /tf_static` show messages when you run the static_transform_publisher?

I've tried doing that echo command and have not been able to get messages to show up (no studio or other tools involved).

**Comment by chenjun00** [comment] 2021-12-05 10:15
According to my understanding, the `/tf_static` seems to be received in a `transform_listener` only once, and then stored to `tf_buffer`, when a node tried to use the static tf, it will go to the `tf_buffer` to seek specified tf. So the command `ros2 topic echo /tf_static` would only show once the tf msg.

@defunctzombie  As for your inability to get msg to show up, I suggest you to run `ros2 topic echo /tf_static` first, then run the `static_transform_publisher`. In this way you would see the static tf msg for one time, which shows that `static_transform_publisher` would only publish once `/tf_static`.

As you can see in the source code:
https://github.com/ros2/geometry2/blob/eaea7a8d7e6812692ef50ca0e68461fed6b77b65/tf2_ros/src/static_transform_broadcaster_node.cpp#L98

**Comment by defunctzombie** [comment] 2021-12-05 15:55
> @defunctzombie As for your inability to get msg to show up, I suggest you to run `ros2 topic echo /tf_static` first, then run the `static_transform_publisher`. In this way you would see the static tf msg for one time, which shows that `static_transform_publisher` would only publish once `/tf_static`.

I also tried this but could not get the message to show up. One note here is that if you just run `ros2 topic echo /tf_static` first without launching anything you get an error about unknown types. So what I did was launch the publisher, start the echo command, stop the publisher, and launch it again. None of these attempts yielded receiving any `/tf_static` messages.

Are you able to perform the steps above on your system and receive `/tf_static` messages?

**Comment by chenjun00** [comment] 2021-12-06 09:49
> One note here is that if you just run ros2 topic echo /tf_static first without launching anything you get an error about unknown types.

Sorry I forgot this step. And here is all the steps to reproduce:
1. run a `static_transform_publisher` first
2. run the echo command
3. rerun the `static_transform_publisher`

Here is what I got:
![image](https://user-images.githubusercontent.com/57067221/144824545-849b681a-76f0-4e3b-a24a-2ce4c18c898f.png)

**Comment by defunctzombie** [comment] 2021-12-06 19:01
@chenjun00 I think the behavior exposed by the set of steps you and I are running (restarting the publisher after echo command) is exposing an issue with the publisher.

I would expect the following sequence of commands to work:
1. run a `static_transform_publisher`
2. run the echo command

However when I run the above sequence - I never receive any messages on `/tf_static`.
![image](https://user-images.githubusercontent.com/84792/144905535-39383cc2-8778-4dae-a83c-2f7be692d849.png)

That is a problem (and I think a regression? from ROS1 latching topics). With rosbridge (and other subscribers) - the subscriber comes online _after_ the publisher. It looks like that doesn't work for ROS2 static_transform_publisher and the `/tf_static` message is never sent to new subscribers that come online. I don't think its expected that subscribers are online _before_ all publishers so would say this is likely a bug with ROS2.

Do you have other nodes that consume `/tf_static`? Do they come online before or after the static transform publisher?

**Comment by defunctzombie** [comment] 2021-12-06 19:49
Here's a related ros2 issue: https://github.com/ros2/ros2cli/issues/523 Tho it is marked as closed our attempts at reproducing have so far shown that the issue is still a problem: https://github.com/ros2/ros2cli/issues/523#issuecomment-987107534

This would explain why the `/tf_static` messages are not arriving when a subscriber appears after the publisher has started - which a common case with the websocket bridge.

**Comment by chenjun00** [comment] 2021-12-07 08:58
> Do you have other nodes that consume /tf_static? Do they come online before or after the static transform publisher?

@defunctzombie  You can try `ros2 run tf2_ros tf2_echo a b`. Whenever you start it, it can always get the static TF.

![image](https://user-images.githubusercontent.com/57067221/144997932-c3d5065a-f0d3-4f63-834c-e24f29571004.png)

**Comment by defunctzombie** [comment] 2021-12-07 15:00
I think the problem is with how the rosbridge server subscribes to the `/tf_static` topic. As I showed above - if you use a simple `topic echo` you do not get the messages on `/tf_static`; I think additional subscriber options are needed. rosbridge may be missing these options and thus not receiving the `/tf_static` messages when it subscribes and subsequently studio is never receiving the messages.

**Comment by chenjun00** [comment] 2021-12-07 15:25
Yes, it might need `tf_listener` and `tf_buffer` in the rosbridge.

**Comment by jhurliman** [comment] 2021-12-09 18:48
This is fixed with the live ROS 2 connection now (the fix will be included in the patch release coming out shortly). The fix for ROS2 using websocket will need to happen in https://github.com/RobotWebTools/rosbridge_suite

**Comment by chenjun00** [comment] 2021-12-11 12:28
So the problem is `/tf_static` using `Transient local` as its Durability which rosbridge is not supported. Is my understanding correct?

**Comment by defunctzombie** [comment] 2021-12-11 15:10
@chenjun00 Correct. We've fixed the issue in rosbridge: https://github.com/RobotWebTools/rosbridge_suite/pull/690 and now waiting on a new release of rosbridge from the ROS release farm. If you want to run rosbridge from source you will be able to connect from Studio and receive your static TF messages now.

We'll close out this issue once the rosbridge release is published.

**Comment by defunctzombie** [comment] 2022-01-03 19:41
Rosbridge server package is released and available in foxy/galactic/rolling.

**Closed by defunctzombie** 2022-01-03 19:41 UTC
Labels: bug
