### ISSUE TITLE
No hover state on sidebar buttons

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#4142] opened 2022-08-16 17:22 UTC
Regression from https://github.com/foxglove/studio/pull/4024

<table><tr><th>Before</th><th>After</th></tr>
<tr>
<td>

https://user-images.githubusercontent.com/14237/184940341-5e36deba-2229-4a65-af06-7f041148e22d.mov

</td><td>

https://user-images.githubusercontent.com/14237/184940366-6de2470b-7c0a-4caf-990e-ff64f91f65ca.mov

</td></table>

**Comment by defunctzombie** [comment] 2022-08-16 17:23
@2metres should we have a hover state?

**Comment by defunctzombie** [comment] 2022-08-16 17:23
Marking as a _bug_ since it is a regression - we can separately determine whether we want this behavior.

**Closed** 2022-08-23 00:21 UTC
Labels: bug, ux
