### ISSUE TITLE
Image doesn't work  in 1.70.0

### ISSUE THREAD

**Issue by jerry-xie-000** [foxglove/studio#6831] opened 2023-09-15 07:13 UTC
**Description**

- Version: 1.70.0
- Platform: windows 10
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):
mcap file:     you can download here:

https://github.com/foxglove/studio/files/12644247/20230915-150145_0.zip
**Steps To Reproduce**

Image panel topic: **/space/image/bev**, will show error as below:
![Snipaste_2023-09-18_09-59-06](https://github.com/foxglove/studio/assets/13086687/56ed5208-9a25-418f-bcea-9ebe4fd70969)

Show error: Error decoding image: Failed to construct 'ImageData': The source width is zero or not a number.

**Expected Behavior**

This mcap file works well in  1.68.0 and 1.69.0.

**Comment by jtbandes** [comment] 2023-09-15 17:28
I'm not able to download the file from baidu. Can you upload it to GitHub by attaching it to a comment here? You will need to create a .zip or .tar.gz file first. https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by jerry-xie-000** [comment] 2023-09-18 01:47
The mcap file:
[20230915-150145_0.zip](https://github.com/foxglove/studio/files/12644247/20230915-150145_0.zip)

**Comment by snosenzo** [comment] 2023-09-20 18:15
I'm not able to reproduce with your sample file. Everything seems to be working properly on main locally, I'm not seeing the error you're getting on the image topic.
<img width="1720" alt="image" src="https://github.com/foxglove/studio/assets/10187776/fd614f69-da6b-44a6-a3f0-a4a72a45458c">
using this layout
[foxglove-layout.json.zip](https://github.com/foxglove/studio/files/12676277/foxglove-layout.json.zip)
Would you mind sharing the layout you used?
Also I see you have `sync annotations` and an annotation topic toggled on in your settings in the screenshot, but it doesn't look like there are any `ImageAnnotations` on that topic in the file you shared. When `Sync annotations` is enabled it will prevent the rendering of the image except when the panel has received a message from each Annotation topic with the exact same timestamp as the image. This could explain why some of the image panels aren't showing images, but it wouldn't explain the error you're getting on the "Image topic" about the "source width" (not sure what would've caused that).

**Comment by jerry-xie-000** [comment] 2023-09-21 02:49
Ok, thanks. Now I understand the "Sync annotations" feature.

I use your layout, and it works.  

Here is my layout, I think it can reproduce the "source width" issue.
[space920.zip](https://github.com/foxglove/studio/files/12679516/space920.zip)

**Comment by snosenzo** [comment] 2023-09-21 14:03
@jerry-xie-000 I'm still not seeing the "source width" issue with your layout. The image panel showing the `/od/front` message has sync annotations turned on still, which is why it's not showing. That error could be because of errant data within a certain source. Are you still encountering this issue?

**Comment by jerry-xie-000** [comment] 2023-09-22 16:30
I reproduce this mcap file on three other computers:  both Win10 and Win11, however the issue is still. 

I also redownload the new version 1.71, the issue is still too.

It seems the issue is easy to be reproduced. Maybe you can try on other computer?

**Comment by snosenzo** [comment] 2023-09-22 16:58
@jerry-xie-000  thanks for the info. I'll test on some other systems. Just a few more questions: are you encountering this error in the desktop version of the app or in the web version or both? If you're using the web version, are you also using chrome?

**Comment by snosenzo** [comment] 2023-09-22 17:24
Ah I just tested on our desktop app and I do see the error on both Win10 and Mac. It doesn't look like it shows up in the browser app though. Will investigate and get it fixed. Thanks for the additional info.

**Comment by snosenzo** [comment] 2023-09-26 20:21
Looks like it was actually fixed in this [PR](https://github.com/foxglove/studio/pull/6885). Which is in production on the web version at studio.foxglove.dev, and will be in the next desktop release (after 1.71.0). Feel free to open this back up if you're still seeing it though

**Closed by snosenzo** 2023-09-26 20:21 UTC
Labels: bug
