### ISSUE TITLE
Automatically select a follow frame when selecting a marker topic

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#2401] opened 2021-12-15 22:58 UTC
**Description**
When a user selects their first marker in an empty 3d panel (or when there is no follow frame selected), automatically assign a follow frame based on the user selection.

**Comment by defunctzombie** [comment] 2021-12-15 22:59
Blocked on https://github.com/foxglove/studio/issues/2400

**Comment by jtbandes** [comment] 2021-12-17 19:14
Duplicate of https://github.com/foxglove/studio/issues/2338

**Closed by jtbandes** 2021-12-17 19:14 UTC
Labels: ux, panel: 3d

**Comment by jtbandes** [comment] 2021-12-17 19:17
Why was this blocked on #2400?
