### ISSUE TITLE
Loading a link from data platform does not populate the plot with data

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#2545] opened 2021-12-27 17:07 UTC
When I open a data platform link in a layout which includes a plot panel I had hoped to be able to see a plot of my data over the entire range I've opened in Studio. Instead I have to start "playing" before the plot panel displays any data (similar to a live connection).

This might be a regression with the data platform data source in Studio.

In adding this feature we should also add subscriber hints. A panel can indicate that a topic should be subscribed to greedily (or whatever hint word we want to use). This would tell the underlying data source to opportunistically fetch the topic beyond the short buffer. This will help us prioritize loading the greedy data before loading the topics that only need the "current" message to display.

**Comment by jtbandes** [comment] 2022-01-03 19:00
> This might be a regression with the data platform data source in Studio.

Nope, never implemented: #1964

**Comment by jtbandes** [comment] 2022-01-31 21:55
Duplicate of #1964

**Closed by jtbandes** 2022-01-31 21:55 UTC
Labels: feature
