### ISSUE TITLE
Looping toggle does not persist when restarting Studio

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#4644] opened 2022-10-14 18:00 UTC
The "loop playback" toggle always resets to off when restarting Studio, regardless of user setting. The playback rate control on the same playback bar does get remembered across sessions, though.

**Comment by jtbandes** [comment] 2022-10-14 18:08
Duplicate of https://github.com/foxglove/studio/issues/2594. Should we reopen that issue?

**Comment by jtbandes** [comment] 2022-10-14 18:09
Duplicate of #2594

**Closed by jtbandes** 2022-10-14 18:09 UTC
Labels: bug, ux
