### ISSUE TITLE
Opening a URL with a layoutID for a layout I do not have tells me to select a layout

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#3179] opened 2022-04-12 20:26 UTC
* Sign in to your foxglove account.
* Open studio.foxglove.dev and let the layouts sync.
* Open https://studio.foxglove.dev/?layoutId=ea800f2c-f854-49de-8ef1-a2f7e1f31719 and the layout should open
* Delete all the localstorage items for cached remote layouts and refresh the page. The layout will not open and you'll see a `Select a layout in the sidebar to get started!` message.

This is a bad experience because when I make a new shared layout and send it to a team member to view they can't open the link.

**Comment by foxymiles** [comment] 2022-04-18 16:41
Is this the same as #3119 ?

**Comment by jtbandes** [comment] 2022-04-18 16:42
Seems like it to me

**Comment by jtbandes** [comment] 2022-04-18 16:53
Duplicate of https://github.com/foxglove/studio/issues/3119

**Closed by jtbandes** 2022-04-18 16:53 UTC
Labels: bug
