### ISSUE TITLE
Loading nav_msgs/msg/Odometry type to the 3D panel

### ISSUE THREAD

**Issue by Gdanan** [foxglove/studio#4962] opened 2022-12-12 09:41 UTC
Hey all,
I'm using ros2, When I load my bag file, I can't see my topic in the "Topics" section in the 3d panel settings.
what can be the cause? the topic name is - /myrobot17/odometry/filtered

**Comment by jtbandes** [comment] 2022-12-12 18:26
The 3D panel does not natively support nav_msgs/Odometry. As a workaround, you could use a [user script](https://foxglove.dev/docs/studio/panels/user-scripts) or [message converter](https://foxglove.dev/docs/studio/extensions/guide-create-message-converter) to convert your data to something it can display.

Duplicate of #1629

**Closed by jtbandes** 2022-12-12 18:26 UTC
