### ISSUE TITLE
Text Input on Settings Gradient Picker doesn't submit on blur or return key

### ISSUE THREAD

**Issue by 2metres** [foxglove/studio#4667] opened 2022-10-19 00:30 UTC
**Description**
Text Input on Settings Gradient Picker doesn't submit on blur or return key, Observed in the Indicator panel

- Version:
- OS: Web, MacOS, Chrome 106
- Data source: Demo Bag

**Steps To Reproduce**

https://user-images.githubusercontent.com/924528/196569728-59d2ada9-b830-4d80-b810-a19fcc8a8b96.mov

**Expected Behavior**
Blur or enter should set value

**Comment by osaro-imohe** [comment] 2022-10-20 13:08
I'll get this

**Comment by jtbandes** [comment] 2022-11-08 21:30
@osaro-imohe Since there's been no update on this issue I'm going to remove your assignment for now

**Comment by snosenzo** [comment] 2022-11-14 16:17
Able to only reproduce partially. Maybe this behavior has changed in the past month?
This is the experience that I am seeing:
 - On changing the value in the gradient picker, the value in the settings is immediately reflective of the change. The gradient picker remains open while the value in the settings is changing.
 - Closing of the gradient picker onBlur is working, but on enter it is not closing (can address in PR)
 - changing the value via the textbox in the gradient picker only updates the settings, but does not update the panel (will address as part of PR). Clicking and dragging over the colorspace to choose a color fixes this.

Let me know if this aligns with your current experience

**Closed** 2022-11-14 22:53 UTC
Labels: bug, good first issue
