### ISSUE TITLE
Playhead is not at the beginning when loading a bag

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#4088] opened 2022-08-10 03:44 UTC
**Description**
The playhead appears slightly offset from the beginning of the bag when loading a bag, although the player starts paused and no data is displayed.

<img width="146" alt="image" src="https://user-images.githubusercontent.com/14237/183790462-0a4648c9-f0d6-4441-a83f-bc1d543d5fa9.png">

- Version: latest web
- OS: Chrome macOS
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): https://librealsense.intel.com/rs-tests/TestData/stairs.bag

**Comment by jtbandes** [comment] 2022-08-12 23:21
Downgrading to UX. Sounds like the time displayed on the playhead is accurate.

**Comment by defunctzombie** [comment] 2022-09-06 15:42
This behavior is by design. The intent of this feature is to make an effort to read some messages from the file so the various panels in the UI display some data rather than sitting empty and waiting for the user to start playing before any data is loaded since rarely are all the desired messages at the exact start time of the file (usually only one or two are exactly at the start).

I'm going to close this as not planned. I'll keep an eye out for any user's that surface this as confusing behavior and if we see that we can consider revisiting.

**Closed by defunctzombie** 2022-09-06 15:42 UTC
Labels: ux
