### ISSUE TITLE
Issue calling someNode/set_parameters with callService() function on a double[] parameter

### ISSUE THREAD

**Issue by danclapp4** [foxglove/studio#4077] opened 2022-08-09 13:00 UTC
**Description**
I am trying to make a custom extension that has ROS2 parameter functionality. To do so I am using the callService() function on many ocastions.  I am having trouble using it in this situation.  

When I call the set_parameters service in the command line like so:
```
ros2 service call ex_node/set_parameters rcl_interfaces/srv/SetParameters "parameters: [{name: ex_param, value: {type: 8, double_array_value: [1.0,2.0,3.0]}}]"
```
I am able to set the parameter as intended.  However, when I try to call the same service in my extension with the callService() function, Foxglove does not like the way I am formatting the argument for the double_array_value field.

- Version: Foxglove 1.19.0
- OS: Ubuntu 20.04.4 LTS
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): rosbridge
- ROS distro (if applicable): Galactic

**Steps To Reproduce**

```
context.callService?.("ex_node/set_parameters", {parameters: [{name: "ex_param", value: {type: 8, double_array_value: [1.0, 2.0, 3.0]}}]});
```
**Expected Behavior**
parameter should be set to new value;

**Actual Behavior**
Error: "The 'double_array_value' field must be a set or sequence and each value of type 'float' "

If I try setting the double_array_value field to "[1.0,2.0,3.0]", I get the following error instead:

Error: "rcl_interfaces/SetParameters_Request message requires a sequence<double> for field parameters.value.double_array_value, but got a <class 'str'>"

**Comment by jtbandes** [comment] 2022-08-16 21:27
Duplicate of https://github.com/RobotWebTools/rosbridge_suite/issues/764, fixed by https://github.com/RobotWebTools/rosbridge_suite/pull/777. Thanks!

**Closed by jtbandes** 2022-08-16 21:27 UTC
Labels: bug
