### ISSUE TITLE
Tooltip says "Follow undefined" when there are no coordinate frames to follow

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2466] opened 2021-12-22 03:05 UTC
<img width="125" alt="Screen Shot 2021-12-21 at 2 53 13 PM" src="https://user-images.githubusercontent.com/195374/147028662-1f512a99-b314-4f17-bbf8-15f4e2c37a70.png">

**Comment by defunctzombie** [comment] 2022-01-08 00:14
👍 Will take

**Comment by defunctzombie** [comment] 2022-01-08 01:26
How did you get to this state? I opened some files with no frames and did not have a tooltip show up when I hover on the disabled follow button.

**Comment by defunctzombie** [comment] 2022-01-08 02:01
I haven't been able to reproduce since we landed the various follow changes. If you do encounter weirdness around the tooltip again happy to take another look.

**Closed by defunctzombie** 2022-01-08 02:01 UTC
Labels: bug, ux, panel: 3d
