### ISSUE TITLE
Publishing geometry_msgs/PoseWithCovarianceStamped

### ISSUE THREAD

**Issue by karanchahal** [foxglove/studio#3170] opened 2022-04-11 17:54 UTC
Hello, we are trying to publish on a topic with type `geometry_msgs/PoseWithCoviaranceStamped`

- Version: Latest Foxglove
- OS:

**Steps To Reproduce**

Open up ROS2 foxy terminal, start ROS bridge server and foxglove. Try publishing on a topic with type as given above.
You get a error message:
```
[rosbridge_websocket-1] [ERROR] [1649693602.570203774] [rosbridge_websocket]: [Client 0] [id: publish:/initialPose:88] publish: Message type geometry_msgs/Point does not have a field seq
```

We see that the ros msg types have a seq field in the Header schema which is not supported in ros2 messages.

How should we fix it ? We can manually change the schema in `@foxglove/rosmsgs_msg_common` package and it works as expected but we are wondering why this is happening and if there's a better way to fix it.

Is foxglove not compatible with all ros2 message types ?

**Comment by defunctzombie** [comment] 2022-04-12 21:47
Related: https://github.com/foxglove/studio/issues/2834

**Comment by defunctzombie** [comment] 2022-04-12 21:51
According to @jtbandes this is while trying to publish using the 3d panel pose publishing feature. @karanchahal is that right?

**Comment by karanchahal** [comment] 2022-04-12 22:06
Yes that is correct @defunctzombie

**Comment by jtbandes** [comment] 2022-04-19 22:07
Duplicate of https://github.com/foxglove/studio/issues/2834

**Closed by jtbandes** 2022-04-19 22:07 UTC
Labels: bug
