### ISSUE TITLE
Changes appearing immediately after switching layouts

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#1646] opened 2021-08-16 22:13 UTC
When switching between layouts, the layout sometimes immediately appears modified, even though the user didn't change anything. If you look at the json before/after, sometimes the panel configs that change are actually from panels that aren't present in the layout — this indicates a stale reference to old config being saved under the new layout.

I thought I already fixed this issue in #1425, so not sure if it regressed or just wasn't totally fixed. The logic for `savedDefaultConfig.current` here is supposed to prevent saving data from an old layout after switching.

https://github.com/foxglove/studio/blob/62d8b42e5817e00660015a5baf3144dc2d5f8d7f/packages/studio-base/src/components/Panel.tsx#L189-L198

**Comment by jtbandes** [comment] 2021-09-02 17:39
Still happens sometimes, especially with newly added panels. Example with splitting an existing Welcome panel from the welcome layout:

https://user-images.githubusercontent.com/14237/131890737-96528128-fe50-4cb3-9466-8d66f835ef22.mov

**Comment by jtbandes** [comment] 2021-09-04 03:47
Got another repro:
- Use "inject edit" feature (on a non-selected layout) which directly updates the server by adding a panel to the layout
- Sync to ensure new layout is downloaded
- Switch to the edited layout – changes appear

https://user-images.githubusercontent.com/14237/132081388-dc4786a1-1ad7-403f-ad00-7c84ba75fc18.mov

**Comment by defunctzombie** [comment] 2021-09-04 14:48
@jtbandes that seems like correct behavior to me. The working version is now different than the base. In this case maybe just the default config, but in other cases maybe more changed. If the server version changes the base on a sync I would expect that to be shown as changes compared to the working copy?

**Comment by jtbandes** [comment] 2021-09-04 15:52
> If the server version changes the base on a sync I would expect that to be shown as changes compared to the working copy?

If you’ve never made changes to the layout locally or even clicked on it, someone else changing it on the server shouldn’t result in a modified dot on your machine. Notice in my video the dot doesn’t appear upon sync, but only when loading the layout.

The dot being visible is just “working copy != undefined”. An unmodified layout doesn’t have a working copy, only the baseline

**Comment by defunctzombie** [comment] 2021-09-10 21:42
From our chat - it seems that the issue here is synthetic and would not occur the same way through user interaction. The "inject edit" adds a panel to the layout but fails to add the default config. A user that is working with the app on two computers and adding a layout would not produce the same result since the app will set the default config when the panel is added to the layout.

I'm gonna close this issue since through user interaction this same flow would not occur. If we do find other instances of changes appearing in unexpected ways (or via remote interaction) we should open new issues with reproduction for those.

**Closed by defunctzombie** 2021-09-10 21:42 UTC
Labels: bug
