### ISSUE TITLE
Plot panel memory usage rapidly increases over time, leading to long GC cycles for dense layouts

### ISSUE THREAD

**Issue by DavidXenakis** [foxglove/studio#4801] opened 2022-11-10 21:14 UTC
**Description**
We have been experiencing poor performance and crashes related to runaway memory use. One of the culprits, we believe, is the plot panel. For particularly dense layouts including many plots and series, chrome's performance profile shows memory usage rapidly increasing during playback, even after all data has been loaded and cached. 

Sawtooth memory usage pattern.
<img width="1726" alt="Screen Shot 2022-10-25 at 11 37 13 AM" src="https://user-images.githubusercontent.com/3076080/201206665-09a1b617-692a-4398-bf0c-87b613a294e4.png">

Please investigate whether or not the plot panel's memory footprint can be reduced.

- Version:
- OS: All
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): Any? It repros from the studio.foxglove.dev sample dataset.
- ROS distro (if applicable): n/a

**Steps To Reproduce**
1. Visit https://studio.foxglove.dev/?ds=sample-nuscenes&layoutId=0daa2893-d4b6-4146-a4b7-9285c9637358&time=2018-07-24T03%3A28%3A49.082513669Z
2. Load all the data by playing through the log.
3. Run a performance profile during playback to capture memory usage.

**Expected Behavior**

**Actual Behavior**

**Comment by defunctzombie** [comment] 2022-11-10 21:22
Layout:

<details>
<pre>
{
  "configById": {
    "Plot!39p1t8k": {
      "title": "Plot",
      "paths": [
        {
          "value": "/gps.latitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.longitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.altitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.position_covariance_type",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.column_count",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.row_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.fields[0].offset",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.sec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.nsec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        }
      ],
      "showXAxisLabels": true,
      "showYAxisLabels": true,
      "showLegend": true,
      "legendDisplay": "floating",
      "showPlotValuesInLegend": false,
      "isSynced": true,
      "xAxisVal": "timestamp",
      "sidebarDimension": 240
    },
    "Plot!n93ptq": {
      "title": "Plot",
      "paths": [
        {
          "value": "/gps.latitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.longitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.altitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.position_covariance_type",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.column_count",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.row_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.fields[0].offset",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.sec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.nsec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        }
      ],
      "showXAxisLabels": true,
      "showYAxisLabels": true,
      "showLegend": false,
      "legendDisplay": "floating",
      "showPlotValuesInLegend": false,
      "isSynced": true,
      "xAxisVal": "timestamp",
      "sidebarDimension": 240
    },
    "Plot!2ojg7qw": {
      "title": "Plot",
      "paths": [
        {
          "value": "/gps.latitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.longitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.altitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.position_covariance_type",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.column_count",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.row_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.fields[0].offset",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.sec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.nsec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        }
      ],
      "showXAxisLabels": true,
      "showYAxisLabels": true,
      "showLegend": false,
      "legendDisplay": "floating",
      "showPlotValuesInLegend": false,
      "isSynced": true,
      "xAxisVal": "timestamp",
      "sidebarDimension": 240
    },
    "Plot!19ldvau": {
      "title": "Plot",
      "paths": [
        {
          "value": "/gps.latitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.longitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.altitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.position_covariance_type",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.column_count",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.row_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.fields[0].offset",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.sec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.nsec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        }
      ],
      "showXAxisLabels": true,
      "showYAxisLabels": true,
      "showLegend": false,
      "legendDisplay": "floating",
      "showPlotValuesInLegend": false,
      "isSynced": true,
      "xAxisVal": "timestamp",
      "sidebarDimension": 240
    },
    "Plot!2s45z45": {
      "title": "Plot",
      "paths": [
        {
          "value": "/gps.latitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.longitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.altitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.position_covariance_type",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.column_count",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.row_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.fields[0].offset",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.sec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.nsec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        }
      ],
      "showXAxisLabels": true,
      "showYAxisLabels": true,
      "showLegend": false,
      "legendDisplay": "floating",
      "showPlotValuesInLegend": false,
      "isSynced": true,
      "xAxisVal": "timestamp",
      "sidebarDimension": 240
    },
    "Plot!2pejgzc": {
      "title": "Plot",
      "paths": [
        {
          "value": "/gps.latitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.longitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.altitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.position_covariance_type",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.column_count",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.row_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.fields[0].offset",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.sec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.nsec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        }
      ],
      "showXAxisLabels": true,
      "showYAxisLabels": true,
      "showLegend": false,
      "legendDisplay": "floating",
      "showPlotValuesInLegend": false,
      "isSynced": true,
      "xAxisVal": "timestamp",
      "sidebarDimension": 240
    },
    "Plot!370cv4i": {
      "title": "Plot",
      "paths": [
        {
          "value": "/gps.latitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.longitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.altitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.position_covariance_type",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.column_count",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.row_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.fields[0].offset",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.sec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.nsec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        }
      ],
      "showXAxisLabels": true,
      "showYAxisLabels": true,
      "showLegend": false,
      "legendDisplay": "floating",
      "showPlotValuesInLegend": false,
      "isSynced": true,
      "xAxisVal": "timestamp",
      "sidebarDimension": 240
    },
    "Plot!224joto": {
      "title": "Plot",
      "paths": [
        {
          "value": "/gps.latitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.longitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.altitude",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/gps.position_covariance_type",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.position.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.pose.orientation.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.column_count",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_size.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.row_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.cell_stride",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.fields[0].offset",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.sec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/drivable_area.timestamp.nsec",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.linear_accel.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.w",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.q.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.x",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.y",
          "enabled": true,
          "timestampMethod": "receiveTime"
        },
        {
          "value": "/imu.rotation_rate.z",
          "enabled": true,
          "timestampMethod": "receiveTime"
        }
      ],
      "showXAxisLabels": true,
      "showYAxisLabels": true,
      "showLegend": true,
      "legendDisplay": "floating",
      "showPlotValuesInLegend": false,
      "isSynced": true,
      "xAxisVal": "timestamp",
      "sidebarDimension": 240
    }
  },
  "globalVariables": {},
  "userNodes": {},
  "linkedGlobalVariables": [],
  "playbackConfig": {
    "speed": 1
  },
  "layout": {
    "first": {
      "first": {
        "first": "Plot!39p1t8k",
        "second": "Plot!224joto",
        "direction": "column"
      },
      "second": {
        "first": "Plot!n93ptq",
        "second": "Plot!2ojg7qw",
        "direction": "column"
      },
      "direction": "column"
    },
    "second": {
      "first": {
        "first": "Plot!19ldvau",
        "second": "Plot!2s45z45",
        "direction": "column"
      },
      "second": {
        "first": "Plot!2pejgzc",
        "second": "Plot!370cv4i",
        "direction": "column"
      },
      "direction": "column"
    },
    "direction": "column"
  }
}
</pre>
</details>

**Comment by foxymiles** [comment] 2022-11-14 00:55
Thanks for the detailed report @DavidXenakis . What version of Chrome and what OS are you using to reproduce this?

**Comment by DavidXenakis** [comment] 2022-11-14 17:35
This was reproducible for me on Chrome version 107.0.5304.87 on MacOS Monterey.

**Comment by defunctzombie** [comment] 2022-11-15 05:26
<img width="974" alt="image" src="https://user-images.githubusercontent.com/84792/201833444-7c82de33-55a9-4ac1-b872-57151b94ebeb.png">

I was able to reproduce this result on my mac. The drop in memory occurs when I let playback loop from the start. What I am seeing here looks like memory buildup during playback and release when playback restarts.

**Comment by jtbandes** [comment] 2022-11-23 17:55
This should help a lot once the data has been fully buffered: https://github.com/foxglove/studio/pull/4884

**Comment by jtbandes** [comment] 2022-12-01 00:38
This will help reduce extra renders when seeking: https://github.com/foxglove/studio/pull/4885

**Comment by defunctzombie** [comment] 2022-12-13 02:01
@jtbandes is there further work planned on this or are we waiting for feedback? Do we believe the original issues described are resolved?

**Comment by jtbandes** [comment] 2022-12-13 02:30
We are waiting for feedback.

**Comment by jtbandes** [comment] 2022-12-21 02:37
Got confirmation from @DavidXenakis that memory growth is greatly reduced. Closing out this issue, and any further issues can be tracked separately.

**Closed by jtbandes** 2022-12-21 02:37 UTC
Labels: bug, performance, panel: plot
