### ISSUE TITLE
When I use convertTo field for a subscribed message, allMessages is empty but currentMessage is present

### ISSUE THREAD

**Issue by emresiimseek** [foxglove/studio#6713] opened 2023-08-31 08:20 UTC
When I use convertTo field for a subscribed message, allMessages is empty but currentMessage is present.
The relevant converter has been registered.
allMessages appear when convertTo field is deleted.

- Version:1.68.0
- Platform:Web
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):

**Steps To Reproduce**
![image](https://github.com/foxglove/studio/assets/24704795/77e924a9-cb03-4e3b-a751-28705b071b2a)

```javascript
  useLayoutEffect(() => {
    context.onRender = (render_state: RenderState, done) => {
      setRenderDone(() => done);

      if (render_state.currentFrame) {
        setLocationFix(render_state.currentFrame?.[0]?.message);
      }
    };

    context.watch('currentFrame');
    context.watch('allFrames');
    context.subscribe([{ topic: '/message/message', convertTo: 'foxglove.LocationFix' }]);
  }, [context]);
``` 

**Expected Behavior**

**Comment by foxymiles** [comment] 2023-09-01 14:27
What happens if you set `preload: true` in your `subscribe` call?

**Comment by foxymiles** [comment] 2023-09-12 12:43
Can you please try setting `preload: true` in your subscribe call? I think you will see `allMessages` populated if you do this.

**Comment by foxymiles** [comment] 2023-09-18 12:33
I believe this is working as intended and you'll get the result you want if you pass the `preload: true` flag to your subscribe call. I'll close this for now and we can reopen it if that's not the case.

**Closed by foxymiles** 2023-09-18 12:33 UTC
Labels: bug
